complete -xc get -d "Press any key to continue..." -a "\t"
complete -c get -s p -l prompt -d "Set the prompt <text>"
complete -c get -s r -l rule -d "Set input validation <regex>"
complete -c get -s e -l error -d "Set the error <message>"
complete -c get -l no-cursor -d "Hide cursor"
complete -c get -l no-case -d "Ignore case during validation"
complete -c get -s s -l silent -d "Hide user input as it is typed"
complete -c get -s q -l quiet -d "Enable quite mode"
complete -c get -s h -l help -d "Show usage help"
