#!/bin/env sh

wget \
    --recursive \ # Download the whole site.
    --no-clobber \ # Don't overwrite existing files.
    --page-requisites \ # Get all assets/elements (CSS/JS/images).
    --adjust-extension \ # Save files with .html on the end.
    --span-hosts \ # Include necessary assets from offsite as well.
    --convert-links \ # Update links to still work in the static version.
    --restrict-file-names=windows \ # Modify filenames to work in Windows as well.
    $1
