# Shell variables
# Generated by 'wal'
wallpaper='/home/tomato/.local/share/backgrounds/timovaknar_tciQ-38WQDY.jpeg'

# Special
background='#0E0607'
foreground='#e5c7c6'
cursor='#e5c7c6'

# Colors
color0='#0E0607'
color1='#624041'
color2='#704A4E'
color3='#AE384B'
color4='#9F5F5C'
color5='#C27D80'
color6='#6DCBCC'
color7='#e5c7c6'
color8='#a08b8a'
color9='#624041'
color10='#704A4E'
color11='#AE384B'
color12='#9F5F5C'
color13='#C27D80'
color14='#6DCBCC'
color15='#e5c7c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
