#!/bin/env bash

source "$HOME/.bin/rofi-effects";

if pgrep -x "rofi" > /dev/null; then
    xdotool key Escape
    echo "rofi-running"
else
#height=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*' | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/' |cut -d "x" -f 2)

#fi -show drun -location 7 -yoffset -$((height-301)) -xoffset 0 &
    rofi -show calc -modi calc -no-show-match -no-sort -p calculator -location 1 &
    sleep 0.3
    rofi_window_pop -
fi
