#!/bin/bash

MUSIC_DIR=/mnt/data/Hiburan/Musik

COVER=/tmp/cover.jpg

function reset_background
{
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current -p 6600)"
    file="$(mpc --format %file% current -p 6600)"
    title="$(mpc --format "%artist% - %title%" current -p 6600)"
    mpd_state="$(mpc |awk -F'[][]' '{print $2}' | head -n -1 | tail -n+2)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    covers="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \; )"
    src="$(echo -n "$covers" | head -n1)"
    rm -f "$COVER" 
    if [[ -n "$src" ]] ; then
	convert "$src" -resize 700x "$COVER"
        if [[ -f "$COVER" ]] ; then
           #scale down the cover to 30% of the original
           #printf "\e]20;${COVER};65x65+87+00:op=keep-aspect\a"
           printf "\e]20;${COVER};65x65+45+00:op=keep-aspect\a"
           notify-send --expire-time=2000 -i ${COVER} "$mpd_state" "$title"
        else
            reset_background
            notify-send "$mpd_state" "$title"
        fi
    else
        reset_background
        notify-send "$mpd_state" "$title"
    fi
} &
