#!/bin/env bash

source "$HOME/.bin/albumart";

SIZE="280x280"

main() {
	while true; do
		get_cover
		if [[ -n "$src" ]] ; then
			convert "$src" -resize "$SIZE^" -gravity center -crop $SIZE+0+0 +repage "$COVER"
	    	feh -g $SIZE $COVER &
	    	echo $! >/tmp/cover.pid
		fi
	    mpc idle &> /dev/null
	    kill 9 $(cat /tmp/cover.pid) &> /dev/null
	done	
}

main
