# Shell variables
# Generated by 'wal'
wallpaper='/home/reorr/Pictures/Unsplash/thought-catalog-659825-unsplash.jpg'

# Special
background='#fdf8fc'
foreground='#211D33'
cursor='#211D33'

# Colors
color0='#fdf8fc'
color1='#A61C4D'
color2='#CF074C'
color3='#E1245F'
color4='#A74755'
color5='#E94F6E'
color6='#EC468E'
color7='#211D33'
color8='#948090'
color9='#A61C4D'
color10='#CF074C'
color11='#E1245F'
color12='#A74755'
color13='#E94F6E'
color14='#EC468E'
color15='#211D33'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
