# Shell variables
# Generated by 'wal'
wallpaper='/home/reorr/Pictures/8c7d741363ed3ab8bbd18a2bdcd8647be132e5c52ff9baf0a4f5bbd891f38fe8.jpg'

# Special
background='#181813'
foreground='#adc6bc'
cursor='#adc6bc'

# Colors
color0='#181813'
color1='#38856A'
color2='#5C8F6E'
color3='#939238'
color4='#A29770'
color5='#CA9C74'
color6='#329786'
color7='#adc6bc'
color8='#798a83'
color9='#38856A'
color10='#5C8F6E'
color11='#939238'
color12='#A29770'
color13='#CA9C74'
color14='#329786'
color15='#adc6bc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
