#!/usr/bin/env bash

# ANSI Color -- use these variables to easily have different color
#    and format output. Make sure to output the reset sequence after 
#    colors (f = foreground, b = background), and use the 'off'
#    feature for anything you turn on.

file=$HOME/.cache/wal/colors.Xresources

initializeANSI()
{
  esc=""

  blackf="${esc}[30m";   redf="${esc}[31m";    greenf="${esc}[32m"
  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
  cyanf="${esc}[36m";    whitef="${esc}[37m"
  
  blackb="${esc}[1;30m";   redb="${esc}[1;31m";    greenb="${esc}[1;32m"
  yellowb="${esc}[1;33m"   blueb="${esc}[1;34m";   purpleb="${esc}[1;35m"
  cyanb="${esc}[1;36m";    whiteb="${esc}[1;37m"

  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"

  reset="${esc}[0m"
}

# note in this first use that switching colors doesn't require a reset
# first - the new color overrides the old one.

#for i in {1..8}; do
#  color[i]=$(grep "color$i *:" $file | awk -F\# '{print $2}' | head -1)
#done
color0=$(grep "color0 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color1=$(grep "color1 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color2=$(grep "color2 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color3=$(grep "color3 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color4=$(grep "color4 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color5=$(grep "color5 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color6=$(grep "color6 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color7=$(grep "color7 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')
color8=$(grep "color8 *:" $file | awk -F\# '{print $2}' | head -1| awk '{print toupper($0)}')

numbers (){
initializeANSI

cat << EOF

${blackf}FF$color0${reset} ${redf}FF$color1${reset} ${greenf}FF$color2${reset} ${yellowf}FF$color3${reset} ${bluef}FF$color4${reset} ${purplef}FF$color5${reset} ${cyanf}FF$color6${reset} ${whitef}FF$color7${reset}
${blackb}FF$color0${reset} ${redb}FF$color1${reset} ${greenb}FF$color2${reset} ${yellowb}FF$color3${reset} ${blueb}FF$color4${reset} ${purpleb}FF$color5${reset} ${cyanb}FF$color6${reset} ${whiteb}FF$color7${reset}

EOF

}

blocks (){

initializeANSI

cat << EOF

${blackf}████${reset}${blackb}████${reset} ${redf}████${reset}${redb}████${reset} ${greenf}████${reset}${greenb}████${reset} ${yellowf}████${reset}${yellowb}████${reset} ${bluef}████${reset}${blueb}████${reset} ${purplef}████${reset}${purpleb}████${reset} ${cyanf}████${reset}${cyanb}████${reset} ${whitef}████${reset}${whiteb}████${reset}
${blackf}████${reset}${blackb}████${reset} ${redf}████${reset}${redb}████${reset} ${greenf}████${reset}${greenb}████${reset} ${yellowf}████${reset}${yellowb}████${reset} ${bluef}████${reset}${blueb}████${reset} ${purplef}████${reset}${purpleb}████${reset} ${cyanf}████${reset}${cyanb}████${reset} ${whitef}████${reset}${whiteb}████${reset}
${blackf}████${reset}${blackb}████${reset} ${redf}████${reset}${redb}████${reset} ${greenf}████${reset}${greenb}████${reset} ${yellowf}████${reset}${yellowb}████${reset} ${bluef}████${reset}${blueb}████${reset} ${purplef}████${reset}${purpleb}████${reset} ${cyanf}████${reset}${cyanb}████${reset} ${whitef}████${reset}${whiteb}████${reset}

EOF

}

case $1 in
  b)  blocks;;
  n)  numbers;;
  a)  blocks && numbers;;
  *)  blocks && numbers;;
esac
