#!/bin/env bash

min=0
max=100
curr_alpha=$(xfconf-query -c xfce4-panel -p /panels/panel-1/background-alpha)
arr=()
curr_desktop=$(wmctrl -d | grep -w "*" | cut -d" " -f 1)
for i in `wmctrl -l | grep -w "$curr_desktop" | cut -d' ' -f1`; do
	exist=$(xprop -id "$i" | grep "_NET_WM_STATE(ATOM)" | grep "_NET_WM_STATE_MAXIMIZED_VERT" | grep "_NET_WM_STATE_MAXIMIZED_HORZ" | grep -v "_NET_WM_STATE_HIDDEN")
	if [ -z $exist ]; then
		echo "unmaximized"
	else
		arr[${#arr[@]}]="maximized"
	fi
done
if [ ${#arr[@]} -eq 0 ]; then
	for ((i=$curr_alpha; i>=$min; i--)) ; do
		xfconf-query -c xfce4-panel -p /panels/panel-1/background-alpha -s $i
	done;
else
    for ((i=$curr_alpha; i<=$max; i++)) ; do
		xfconf-query -c xfce4-panel -p /panels/panel-1/background-alpha -s $i
    done;
fi
