# Shell variables
# Generated by 'wal'
wallpaper='/home/tomato/Pictures/1556160331199.jpg'

# Special
background='#fefcfb'
foreground='#383B44'
cursor='#383B44'

# Colors
color0='#fefcfb'
color1='#7C91C3'
color2='#8F9AAC'
color3='#979DA5'
color4='#94A8B4'
color5='#D2BDB5'
color6='#8597C6'
color7='#383B44'
color8='#978e8b'
color9='#7C91C3'
color10='#8F9AAC'
color11='#979DA5'
color12='#94A8B4'
color13='#D2BDB5'
color14='#8597C6'
color15='#383B44'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
